server:
  port: 19001

spring:
  application:
    name: tensquare-base
  rabbitmq:
    host: 192.168.0.100
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.100:3306/tensquare_base?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
    instance-id: tensquare-base-19001

info:
  app.name: tensquare
  company.name: www.panghu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$