server:
  port: 9008

spring:
  application:
    name: tensquare-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.100:3306/tensquare_user?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: 192.168.0.100
    port: 6379
    password: password
  rabbitmq:
    host: 192.168.0.100
    port: 5672
    username: guest
    password: guest

jwt:
  config:
    key: panghu
    ttl: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
    instance-id: tensquare-user-9008


info:
  app.name: tensquare
  company.name: www.panghu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$